# Generated by Django 3.0 on 2020-01-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191231_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-slug'),
            preserve_default=False,
        ),
    ]
