# Generated by Django 3.0 on 2020-01-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200101_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
